title: VSaturn Wiki
description: The official wiki and documentation for VSaturn Downloader.
baseurl: "/Mandrusia/docs" # IMPORTANT: Your repo name + /docs
url: "https://Mandrusian.github.io" # Your GitHub Pages base URL

# Theme settings
theme: minima

# Exclude Jekyll-specific files from the final site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Markdown processor
markdown: kramdown

# Permalinks (how your URLs will look)
permalink: /:title/
